# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74f96a4d4800d33df058549a116444b4abe2b8b7c5598532dfa1d6b4bebcd3933679230040534fd9813f1f88a2ce3ceaf860246ea2ef9870dead564b440da859

test:
  secret_key_base: d684c0d8a5fca6cdcae8742a0ddfa6411c070d6db0401cb5b38f1dcb0f7aa044f4466ba0dea37c74779b5560ff2ba09252ff462ff7704c620ad4cad3852d4b02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
